{% set name = "compressed-rtf" %}
{% set version = "1.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/compressed_rtf-{{ version }}.tar.gz
  sha256: 7c30859334839f3cdc7d10796af5b434bb326b9df7cb5a65e95a8eacb2951b0e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - compressed_rtf

about:
  home: https://github.com/delimitry/compressed_rtf
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Compressed Rich Text Format (RTF) compression and decompression package"
  doc_url: https://msdn.microsoft.com/en-us/library/cc463890(v=exchg.80).aspx
  dev_url: https://github.com/delimitry/compressed_rtf

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar
